cloud:
  aws:
    credentials:
      accessKey: AKIA2WEO23CSTQACHB7O
      secretKey: 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
    s3:
      bucket: signedubucket
    region:
      static: ap-northeast-2
    stack:
      auto: false